services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file:
      - .env
    environment:
      - PYTHONPATH=.
      - AWS_PROFILE=default
    volumes:
      # ソースコードをホストと同期
      - ./app:/app/app
      # AWS認証情報のマウント
      - ~/.aws:/root/.aws
    ports:
      - "8000:8000"
    # 開発時は reload を有効化する（上書き）
    command: uvicorn app.main:app --host 0.0.0.0 --reload